// Kept out of the "use client" content module so the server page can
// read it directly to emit FAQPage JSON-LD.
export const FAQS: { q: string; a: string }[] = [
  { q: "Can I scan barcodes with my phone camera?", a: "Yes. When adding or editing a product, tap the scan icon next to the Barcode field. Your phone's back camera opens, just point it at the barcode on the packaging and it's detected and filled in automatically. Supports EAN-13, EAN-8, UPC-A, UPC-E, Code 128, Code 39, Code 93, and QR codes. You can also type the barcode manually if you prefer." },
  { q: "Can I take product photos without leaving the app?", a: "Yes. In the Add/Edit Product form, tap Take Photo to open your phone's camera directly inside the app. Frame the shot, tap the shutter button, and the photo is set instantly. You can also tap Upload Photo to pick an existing image from your gallery instead." },
  { q: "Can I track inventory with the free plan?", a: "Yes. The free plan includes up to 50 products with full stock tracking, reorder thresholds, low stock alerts, stock adjustment logs, and supplier links. You only need to upgrade when your product count or sales volume grows." },
  { q: "Is there really a free plan?", a: "Yes, permanently free, not a trial. The free plan includes 50 products, 200 sales per month, the full POS, stock adjustments, low stock alerts, unlimited customer and utang tracking, and 2 team members. No credit card required." },
  { q: "How does the POS work?", a: "Open the POS screen, tap any product to add it to the cart, type or use +/− to change quantities. Apply a discount if needed, choose Cash, GCash, Maya, Bank, or Other as the payment method. For cash, enter the amount tendered and the change is calculated instantly. Tap Checkout to complete the sale and deduct stock." },
  { q: "Does it automatically deduct stock when I make a sale?", a: "Yes. Every time you complete a sale through the POS, the stock for each product in the cart is reduced automatically. If you void a sale later, the stock is restored." },
  { q: "What payment methods does the POS support?", a: "Cash and QR. For Cash, enter the amount tendered and the change is calculated instantly. For QR, your uploaded QR code (GCash, Maya, bank, whatever you set up) is shown full-screen for the customer to scan. Once they pay, you tap Payment Received to complete the sale." },
  { q: "How does QR payment work?", a: "Go to Store → QR Setup and upload a screenshot of your GCash, Maya, or bank QR code. From then on, when a customer chooses QR at the POS, your QR code appears on screen with the total amount. The customer scans it on their phone and sends the payment. You tap Payment Received to confirm and complete the sale." },
  { q: "Can I track profit per sale?", a: "Yes. When you add a product, set its cost price. Smapey records that cost at the time of each sale so your profit stays accurate even if you change the price later. You'll see today's profit on the dashboard and a profit column on every sale in your sales history." },
  { q: "Can I record utang (customer credit)?", a: "Yes. Add the customer once, then at the POS pick their name and enter how much they're paying now. Leave it blank to settle in full, or enter a smaller amount, or zero, and the remainder is recorded as their utang. The Customers page shows every balance, and the dashboard shows your total receivable so you always know how much money is still out there." },
  { q: "How do I record a payment on someone's utang?", a: "Open Customers, find the person, and tap Pay. Enter the amount, choose how they paid, and save. The payment is applied to their oldest unpaid sale first, so their balance goes down in the same order the debt built up. You'll see the new balance before you confirm, and each sale flips from Utang to Partial to Paid as it gets settled." },
  { q: "Can I set a credit limit per customer?", a: "Yes, and it's optional. Give a customer a limit and Smapey blocks any POS checkout that would push them past it, showing how much room is left before you ring up the sale. Leave it blank and there's no limit, which suits regulars you already trust." },
  { q: "Is utang tracking included in the free plan?", a: "Yes. Customer records and utang tracking are unlimited on every plan, including the free one. The free plan's limits are on products (50) and sales per month (200), not on how many customers you keep or how much credit you track." },
  { q: "Can I see the history of stock changes?", a: "Yes. The Stock History page lists every movement, restocks, sales, manual adjustments, and stock returned by a voided sale, with the date, quantity, supplier, and any note you added. Filter by product or movement type to trace exactly where a product's stock went." },
]
