// Kept out of the "use client" content module so the server page can read it
// directly to emit FAQPage JSON-LD.
//
// Every answer here describes behaviour that exists in the product today. The
// source design also advertised a tenant portal, online bed booking, PayPal,
// sub-metered utility splits, and a set of dormitory tools - none of which are
// built, so they are not claimed here.
export const FAQS: { q: string; a: string }[] = [
  { q: "What is a boarding house management system?", a: "It is software a landlord or property manager uses to run a rental property at the room and bed level rather than on paper. It holds tenant profiles, assigns each boarder to a room and a bed, generates the monthly bill, records payments, splits utility bills, and keeps a permanent record of who stayed where and what they paid." },
  { q: "Can I charge different rates for upper and lower deck beds?", a: "Yes. In a bedspace room each bed is its own record with its own name and monthly rate, so a lower deck can be priced above an upper deck in the same room. When a tenant moves into a bed their rent defaults to that bed's rate." },
  { q: "How do tenants report maintenance problems?", a: "Each room has a printable QR code poster. Tenants scan it with their phone camera - no app and no account - and submit a short report with up to three photos. It appears on your Maintenance page tagged with the reporter's name, and the page also shows the room's recent reports and their status so nobody re-reports something already being fixed." },
  { q: "Which payment methods can I record?", a: "Cash, GCash, Maya, bank transfer, and an Other option for anything else. Partial payments are supported - a ₱2,000 payment against a ₱4,500 bill leaves a ₱2,500 balance on the ledger and the bill stays open." },
  { q: "How are shared utility bills split?", a: "One electric or water bill is entered for the room and each tenant's statement shows their share, which is the room's bill divided by the number of tenants in it, with the computation spelled out. Each share is fixed when the bill is created, so a roommate paying early never changes what anyone else owes." },
  { q: "Can tenants pay and report the payment themselves?", a: "Yes. Each room's poster can carry your GCash or bank QR beside the report QR. A tenant scans, types their name, and sees their exact balance for the month - rent plus their own share of each utility. They pay, attach a screenshot, and submit. It arrives in your Payments Inbox and one tap posts it to the correct rent and utility bills." },
  { q: "Are tenants notified of their monthly bill?", a: "Creating the month's bills emails each tenant with an address a statement showing rent, their share of the room's utilities with the computation, the total, and the due date." },
  { q: "Can tenants transfer or swap rooms and beds?", a: "Yes. A transfer moves a tenant to any vacant room or bed with the deposit carried over, and a swap lets two tenants trade places in one step even when there is no vacancy. Every movement is kept in stay history with its dates and rates." },
  { q: "Is there a statement of account per tenant?", a: "Yes, the Tenant Ledger. One click shows the move-in date, the deposit and its status, every room and bed the tenant has occupied including transfers and swaps, and a month-by-month payment table with billed, paid, balance, and running totals." },
  { q: "How is occupancy rate calculated?", a: "Occupied beds or slots divided by total capacity. For bedspace rooms capacity is the number of beds, so a room with one free upper deck reads as partly vacant rather than full. It updates the moment someone moves in or out." },
  { q: "Does it track expenses and profit?", a: "Yes. The Cashflow page is an automatic cashbook - rent, utility payments, and deposits flow in on their own, repairs and expenses are logged in seconds, and each month shows Money In, Money Out, and Net with a running balance." },
  { q: "Is my data separate from other boarding houses?", a: "Yes. Every record belongs to your organisation and is scoped to it, so rooms, tenants, bills, and history are never visible to another operator." },
  { q: "Is it really free?", a: "Yes. The free plan covers 5 rooms and 20 tenants with no card required, including rooms and beds, tenants, rent billing, utility billing, and maintenance with QR reporting. Paid plans raise the limits when you outgrow it." },
]
