// Kept out of the "use client" content module so the server page can
// read it directly to emit FAQPage JSON-LD.
export const FAQS: { q: string; a: string }[] = [
  { q: "What is a catering management and billing system?", a: "A catering management and billing system combines event booking management with payment tracking in one tool. It handles client registration, quotations, event booking, package pricing and extra charges, payment milestone creation and collection, recipes and supply costs, and staff payouts, replacing separate spreadsheets, paper records, and manual invoicing." },
  { q: "How does billing work in Smapey's catering system?", a: "Billing is milestone-based per booking. You create milestones for each booking (e.g., 30% reservation fee, 50% partial payment two weeks before the event, 20% balance on event day). Each milestone records the amount, due date, payment method, and paid/unpaid status. Your client sees the same schedule on their quote, and the dashboard counts your pending and overdue payments." },
  { q: "Does the billing system support partial payments?", a: "Yes, through milestones. Split the bill into as many milestones as you need (a reservation fee, one or more partial payments, and the balance) and mark each one paid as the money comes in. Each milestone is Pending, Paid, or Overdue. This matches how Philippine catering payments typically work, since clients rarely pay in full upfront." },
  { q: "What payment methods can I log?", a: "You can record collections as Cash, GCash, Maya, Bank Transfer, Check, or Other. Smapey doesn't process payments, it records what you collect and keeps your milestone history accurate." },
  { q: "Is there a difference between the management system and billing system?", a: "In Smapey, they're the same system. The catering management side (quotes, bookings, the calendar, recipes and market lists, staff) and the billing side (payment milestones, charges and discounts, collections, revenue tracking) work together. You don't need separate software for each." },
  { q: "Is it free?", a: "Yes, Smapey's free plan includes catering management and billing for small catering businesses. Upgrade to PRO or ENTERPRISE when your business needs higher limits." },
]

