// Kept out of the "use client" content module so the server page can
// read it directly to emit FAQPage JSON-LD.
export const FAQS: { q: string; a: string }[] = [
  { q: "What does a boarding house management system do?", a: "It replaces spreadsheets and paper records by centralizing room and bed setup, tenant registration, move-in/move-out tracking, monthly rent billing, utility billing, payment recording, maintenance requests, and occupancy analytics in one dashboard. Philippine boarding house owners use it to collect rent faster and reduce manual follow-up." },
  { q: "Can it handle bedspace with different deck rates?", a: "Yes. In a bedspace room you add each bed by name (Lower A, Upper A) with its own monthly rate. When a tenant moves into a bed, their rent defaults to that bed's rate, so lower-deck and upper-deck pricing is handled automatically." },
  { q: "How do tenants report maintenance problems?", a: "Each room has a printable QR code poster. Tenants scan it with their phone camera (no app or account needed) and submit a short report with up to 3 photos. It appears on the owner's Maintenance page instantly with an in-app notification, tagged with the reporter's name. The report page also shows the room's recent reports and their status, so tenants don't re-report issues that are already being fixed." },
  { q: "Can the system separate rent from utilities?", a: "Yes. Rent bills and utility bills are created separately so tenants always know which amount is rent and which is for electricity or water. Both types appear on the dashboard's revenue breakdown." },
  { q: "Does it support partial payments?", a: "Yes. You can record partial payments on any rent or utility bill. The system calculates the outstanding balance and marks the bill as partially paid. Overdue balances surface automatically on the dashboard." },
  { q: "Is there a per-tenant statement of account?", a: "Yes, the Tenant Ledger. One click shows a tenant's original move-in date, deposit and its status, every room and bed they've occupied including transfers and swaps, and a month-by-month payment table with billed, paid, balance, and running totals." },
  { q: "Are tenants notified of their monthly bill?", a: "Yes. Creating the month's bills automatically emails each tenant a billing statement: rent, their share of the room's utilities (split evenly per tenant in shared and bedspace rooms, with the computation shown), the total, and the due date." },
  { q: "Does it track expenses and profit?", a: "Yes. The Cashflow page is an automatic cashbook: rent, utility payments, and deposits flow in on their own, repairs and expenses are logged in seconds, and each month shows Money In, Money Out, and Net with a running balance." },
  { q: "Can tenants pay and report online?", a: "Yes. Each room's poster carries two QR codes - one to pay (your GCash or bank QR) and one to report the payment. A tenant scans, types their name, and sees their exact balance for the month, rent plus their own split of each utility, computed automatically. They pay, attach a screenshot, and submit with no app or login. It arrives in your Payments Inbox with a live unread badge, and one tap posts it to the correct rent and utility bills." },
  { q: "Can tenants change rooms or beds?", a: "Yes. Transfer moves a tenant to any vacant room or bed with the deposit carried over, and Swap lets two tenants trade places in one step even when there's no vacancy. Every movement is preserved in Stay History with dates and rates." },
  { q: "How is occupancy rate calculated?", a: "The system counts every occupied bed or slot against total capacity, for bedspace rooms, capacity is the number of beds. Occupancy rate is shown as a percentage on the dashboard and updates the moment someone moves in or out." },
  { q: "Is it free to use?", a: "Yes, Smapey Boarding House Manager has a free plan. You can manage rooms and beds, tenants, rent billing, utility billing, and maintenance tracking with QR reporting at no cost. Upgrade to PRO or ENTERPRISE when your boarding house needs more capacity." },
]

