// Kept out of the "use client" content module so the server page can
// read it directly to emit FAQPage JSON-LD.
export const FAQS: { q: string; a: string }[] = [
  { q: "Is there a free plan?", a: "Yes, and it does not expire. The Free plan covers 200 cars a month with two team members, which is enough to run a small shop's counter properly. No credit card is asked for at signup." },
  { q: "Does it work for a motor wash?", a: "Yes. When you set up, you pick what the shop washes: cars, motorcycles, or both. A motor wash starts with Motorcycle and Big bike sizes and motorcycle services, a car wash starts with sedan, SUV, pick-up and van sizes, and a shop that does both gets all of them. You can add, rename or retire any size or service later." },
  { q: "Do I need to install anything?", a: "No. Smapey runs in the browser on a phone, a tablet at the counter or a laptop, so there is nothing to install or keep updated. The waiting-area display opens in any browser on a smart TV or a laptop plugged into a TV." },
  { q: "How does the price board work?", a: "Your prices live in one grid of services by vehicle size. At the counter, staff tap a package and any add-ons and the price comes from the board, so nobody types an amount. An empty box means you don't offer that service for that size. A new board starts filled with typical Philippine prices, and it asks you to check them until you save your own or confirm they're yours." },
  { q: "Can my staff change a price at the counter?", a: "Only the owner or an admin can charge something other than the board price, and they have to say why. Every change is recorded with who made it, and the owner sees price changes on the dashboard and in Analytics." },
  { q: "How is each washer's share worked out?", a: "You choose how the crew is paid: a percentage of what each car paid, after any discount, or a fixed amount per car. A car's share is split evenly between everyone who washed it and is earned when the car is released. Anyone can have their own rate instead of the shop's, services like an air freshener sold at the counter can be left out of the share, and the payout report for any range of days exports to Excel." },
  { q: "What does closing the day do?", a: "It works out what the drawer should hold: the opening cash plus the cash taken for released cars, less expenses and crew pay taken out of the drawer. You count the cash, bill by bill if you like, and it shows whether you're short or over. GCash, Maya, card and bank payments are listed separately because they never touch the drawer. Once a day is closed, cars can't be added, paid or released on it and its expenses can't change, until the owner or an admin reopens it and says why." },
  { q: "Can customers check on their car?", a: "Yes. Each ticket has a QR code and a link the customer can open on their phone without an account. It shows their queue number, how many cars are ahead, the status and the amount due, and refreshes on its own. It never shows staff notes, other customers or anyone's phone number." },
  { q: "How does the stamp card work?", a: "Set how many washes earn a free one and which service is free. The count lives on the plate, so there is no paper card to lose. When a car has earned it, the counter sees Free wash available, and the customer sees their stamps on their status link." },
  { q: "What payment methods can I record?", a: "Cash, GCash, Maya, card and bank transfer. Each car is marked paid with how it was paid, and the day's closing counts only the cash." },
]
