// Kept out of the "use client" content module so the server page can
// read it directly to emit FAQPage JSON-LD.
export const FAQS: { q: string; a: string }[] = [
  { q: "Is there a free plan?", a: "Yes. The Free plan covers two barbers and 200 customer visits a month, which is enough to run a small shop's line properly. No credit card is asked for at signup. The Free plan doesn't include a monthly allowance of text messages; the paid plans below show what each one adds." },
  { q: "Do I need to install anything?", a: "No. Smapey runs in the browser on a phone, a tablet at the counter or a laptop, so there is nothing to install or keep updated. The waiting-area display opens in any browser on a smart TV or a laptop plugged into a TV." },
  { q: "How does the walk-in queue work?", a: "Add each customer as they walk in, with the barber they want or Anyone, and the services they're having. They get a queue number, and the line shows the wait each customer faces, worked out from each barber's line and how long each service takes. When a chair frees up, Call next picks the right customer: the barber's own customers first, then whoever will take anyone." },
  { q: "How is each barber's share worked out?", a: "Set the shop's commission rate once, and give any barber their own rate if they're on a different split. When a customer pays, the barber's share is worked out from the services on the bill. You choose which services earn a share, and products earn one only if you set a share for that product. Closing shows each barber's share for the day, and the report exports to Excel." },
  { q: "Can customers join the line from their phone?", a: "Yes, if you switch it on. Your shop gets its own page, from a link or a printable QR poster, showing whether you're open, the wait right now and your services with prices. Customers join with a name and mobile number and pick a barber or Anyone. They keep their place but show as on the way, and Call next skips them until staff mark them here. Joining closes when the shop is closed, when the line is too long to finish before closing, or when too many people are already on their way." },
  { q: "Can customers book a time and pay a deposit?", a: "Bookings are optional and off until you turn them on. A customer picks a barber, a day up to two weeks ahead and a free half-hour, with at least an hour's notice. If you ask for a deposit, they send it to your own GCash and type the reference number; staff check your GCash and mark it received, and it comes off the bill at payment. Smapey never holds the money." },
  { q: "Does it send text messages?", a: "Yes. Staff can text a customer that they're next with one tap, and customers who agreed to reminders get a text when it's been a while since their last cut, after 21 days unless you change it. Texts come out of your plan's monthly allowance first, then your text credits, and the Free plan has no monthly allowance. For now texts reach Globe and TM numbers only, and other numbers are marked as unreachable before staff try." },
  { q: "Can I sell pomade and other products?", a: "Yes. Add products with their price and stock. Sell them on a haircut's bill or on their own from the Queue, and the stock comes off with every sale and goes back if a payment is undone. Record deliveries and corrections with a history of every change, and the Products page warns you when something runs low." },
  { q: "What can my staff see?", a: "Staff run the Queue and can see customers, barbers, services, and product prices and stock. Analytics, what you paid for products, the online page settings and the day's closing are for the owner, and staff can't change product prices or stock." },
  { q: "What does Analytics show?", a: "For this week, this month, last month or any dates: customers, sales and average spend, how many regulars came back, services and products apart from discounts and the barbers' share, sales by day, your busiest days and hours, top services and products, each barber's sales, share and usual time in the chair, the average wait, results from your online page, and products running low." },
]
